name: docs

on:
  push:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build docs
        # Cambia la línea siguiente para apuntar a tu fork/branch corregido si aún no arreglan upstream
        uses: MariaGrado/tt-gds-action@fix/upload-artifact-v4
