name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build GDS
        # Cambiar referencia al fork/branch corregido si hace falta
        uses: MariaGrado/tt-gds-action@fix/upload-artifact-v4

  viewer:
    needs: gds
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      # Cambiar referencia a la acción viewer corregida en tu fork si aplica
      - uses: MariaGrado/tt-gds-action/viewer@fix/upload-artifact-v4
